/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as LaneInvitesTokenRouteImport } from './routes/lane-invites/$token'
import { Route as AppLanesLaneIdRouteImport } from './routes/_app/lanes/$laneId'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppProjectsProjectIdRouteImport } from './routes/_app/projects/$projectId'
import { Route as AppSettingsGithubRouteImport } from './routes/_app/settings/github'
import { Route as AppSettingsScratchEnvironmentRouteImport } from './routes/_app/settings/scratch-environment'
import { Route as AppSettingsSecretsRouteImport } from './routes/_app/settings/secrets'
import { Route as AppLaneInvitesTokenAcceptRouteImport } from './routes/_app/lane-invites/$token/accept'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const LaneInvitesTokenRoute = LaneInvitesTokenRouteImport.update({
  id: '/lane-invites/$token',
  path: '/lane-invites/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppLanesLaneIdRoute = AppLanesLaneIdRouteImport.update({
  id: '/lanes/$laneId',
  path: '/lanes/$laneId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppProjectsProjectIdRoute = AppProjectsProjectIdRouteImport.update({
  id: '/$projectId',
  path: '/$projectId',
  getParentRoute: () => AppProjectsRoute,
} as any)
const AppSettingsGithubRoute = AppSettingsGithubRouteImport.update({
  id: '/settings/github',
  path: '/settings/github',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsScratchEnvironmentRoute =
  AppSettingsScratchEnvironmentRouteImport.update({
    id: '/settings/scratch-environment',
    path: '/settings/scratch-environment',
    getParentRoute: () => AppRoute,
  } as any)
const AppSettingsSecretsRoute = AppSettingsSecretsRouteImport.update({
  id: '/settings/secrets',
  path: '/settings/secrets',
  getParentRoute: () => AppRoute,
} as any)
const AppLaneInvitesTokenAcceptRoute =
  AppLaneInvitesTokenAcceptRouteImport.update({
    id: '/lane-invites/$token/accept',
    path: '/lane-invites/$token/accept',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/projects': typeof AppProjectsRouteWithChildren
  '/lane-invites/$token': typeof LaneInvitesTokenRoute
  '/lanes/$laneId': typeof AppLanesLaneIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/settings/github': typeof AppSettingsGithubRoute
  '/settings/scratch-environment': typeof AppSettingsScratchEnvironmentRoute
  '/settings/secrets': typeof AppSettingsSecretsRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/lane-invites/$token/accept': typeof AppLaneInvitesTokenAcceptRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/lane-invites/$token': typeof LaneInvitesTokenRoute
  '/': typeof AppIndexRoute
  '/lanes/$laneId': typeof AppLanesLaneIdRoute
  '/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/settings/github': typeof AppSettingsGithubRoute
  '/settings/scratch-environment': typeof AppSettingsScratchEnvironmentRoute
  '/settings/secrets': typeof AppSettingsSecretsRoute
  '/projects': typeof AppProjectsIndexRoute
  '/lane-invites/$token/accept': typeof AppLaneInvitesTokenAcceptRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/setup': typeof SetupRoute
  '/_app/projects': typeof AppProjectsRouteWithChildren
  '/lane-invites/$token': typeof LaneInvitesTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/lanes/$laneId': typeof AppLanesLaneIdRoute
  '/_app/projects/$projectId': typeof AppProjectsProjectIdRoute
  '/_app/settings/github': typeof AppSettingsGithubRoute
  '/_app/settings/scratch-environment': typeof AppSettingsScratchEnvironmentRoute
  '/_app/settings/secrets': typeof AppSettingsSecretsRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/lane-invites/$token/accept': typeof AppLaneInvitesTokenAcceptRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/setup'
    | '/projects'
    | '/lane-invites/$token'
    | '/lanes/$laneId'
    | '/projects/$projectId'
    | '/settings/github'
    | '/settings/scratch-environment'
    | '/settings/secrets'
    | '/projects/'
    | '/lane-invites/$token/accept'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/setup'
    | '/lane-invites/$token'
    | '/'
    | '/lanes/$laneId'
    | '/projects/$projectId'
    | '/settings/github'
    | '/settings/scratch-environment'
    | '/settings/secrets'
    | '/projects'
    | '/lane-invites/$token/accept'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/setup'
    | '/_app/projects'
    | '/lane-invites/$token'
    | '/_app/'
    | '/_app/lanes/$laneId'
    | '/_app/projects/$projectId'
    | '/_app/settings/github'
    | '/_app/settings/scratch-environment'
    | '/_app/settings/secrets'
    | '/_app/projects/'
    | '/_app/lane-invites/$token/accept'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SetupRoute: typeof SetupRoute
  LaneInvitesTokenRoute: typeof LaneInvitesTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/lane-invites/$token': {
      id: '/lane-invites/$token'
      path: '/lane-invites/$token'
      fullPath: '/lane-invites/$token'
      preLoaderRoute: typeof LaneInvitesTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/lanes/$laneId': {
      id: '/_app/lanes/$laneId'
      path: '/lanes/$laneId'
      fullPath: '/lanes/$laneId'
      preLoaderRoute: typeof AppLanesLaneIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/projects/$projectId': {
      id: '/_app/projects/$projectId'
      path: '/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof AppProjectsProjectIdRouteImport
      parentRoute: typeof AppProjectsRoute
    }
    '/_app/settings/github': {
      id: '/_app/settings/github'
      path: '/settings/github'
      fullPath: '/settings/github'
      preLoaderRoute: typeof AppSettingsGithubRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/scratch-environment': {
      id: '/_app/settings/scratch-environment'
      path: '/settings/scratch-environment'
      fullPath: '/settings/scratch-environment'
      preLoaderRoute: typeof AppSettingsScratchEnvironmentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/secrets': {
      id: '/_app/settings/secrets'
      path: '/settings/secrets'
      fullPath: '/settings/secrets'
      preLoaderRoute: typeof AppSettingsSecretsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lane-invites/$token/accept': {
      id: '/_app/lane-invites/$token/accept'
      path: '/lane-invites/$token/accept'
      fullPath: '/lane-invites/$token/accept'
      preLoaderRoute: typeof AppLaneInvitesTokenAcceptRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppProjectsRouteChildren {
  AppProjectsProjectIdRoute: typeof AppProjectsProjectIdRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppProjectsRouteChildren: AppProjectsRouteChildren = {
  AppProjectsProjectIdRoute: AppProjectsProjectIdRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppProjectsRouteWithChildren = AppProjectsRoute._addFileChildren(
  AppProjectsRouteChildren,
)

interface AppRouteChildren {
  AppProjectsRoute: typeof AppProjectsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppLanesLaneIdRoute: typeof AppLanesLaneIdRoute
  AppSettingsGithubRoute: typeof AppSettingsGithubRoute
  AppSettingsScratchEnvironmentRoute: typeof AppSettingsScratchEnvironmentRoute
  AppSettingsSecretsRoute: typeof AppSettingsSecretsRoute
  AppLaneInvitesTokenAcceptRoute: typeof AppLaneInvitesTokenAcceptRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppProjectsRoute: AppProjectsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppLanesLaneIdRoute: AppLanesLaneIdRoute,
  AppSettingsGithubRoute: AppSettingsGithubRoute,
  AppSettingsScratchEnvironmentRoute: AppSettingsScratchEnvironmentRoute,
  AppSettingsSecretsRoute: AppSettingsSecretsRoute,
  AppLaneInvitesTokenAcceptRoute: AppLaneInvitesTokenAcceptRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SetupRoute: SetupRoute,
  LaneInvitesTokenRoute: LaneInvitesTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
